export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';

export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT';

export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';